# Generated by Django 4.2.15 on 2024-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_event_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
