# Generated by Django 4.2.15 on 2024-10-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.venue"
            ),
        ),
    ]
